# config/application.yml
defaults: &defaults
  app_name: LifeBills  
  default_items:
    - name: 早餐
      flag: 0
    - name: 工资
      flag: 1
  default_people:
    - name: 无
  default_accounts:
    - name: 无
  bill_types:
    outlay: 0
    income: 1    
    lend: 2
    borrow: 3
  weixin_token:
  base_url: "http://life-bills.arnkorty.info"
  admin_emails:
    - arnkorty.fu@gmail.com
  bill_types_zh:
    - 支出
    - 收入
    - 借出
    - 归还
development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
